language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - mysql -e 'CREATE DATABASE FableTest;'
addons:
  code_climate:
    repo_token: b0b7492746ebd2075419cab324ea69ab4f444baeb687a1e4cad47e04216af7f6
after_success:
  - npm run coverage
after_script:
  - cat coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack: paviateam:C1q99hL9XXpiPpau2PUrVZPC